version: '3.7'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: schrapert/app
    volumes:
     - .:/var/www/html
    ports:
      - "${APP_PORT}:80"
    networks:
     - schrapert_network
  test-web-server:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: schrapert/app
    volumes:
      - .:/var/www/html
    ports:
      - "${TEST_SERVER_PORT}:80"
    networks:
      - schrapert_network
networks:
  schrapert_network:
    driver: "bridge"
