version: '3.7'
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: php
    volumes:
     - .:/var/www/html
    ports:
      - "${APP_PORT}:80"
    networks:
      - schrapert_network
  test-web-server:
    image: richarvey/nginx-php-fpm
    volumes:
      - ./tests/Server:/var/www/html
    ports:
      - "${TEST_SERVER_PORT}:80"
    networks:
      - schrapert_network
networks:
  schrapert_network:
    driver: "bridge"
